### PR TITLE
Add country flag emoji

### PR DESCRIPTION
**Pull request by livedo**
```javascript
var countries = require('country-data').countries
countries['FI'].emoji
// => 🇫🇮'
```

### CODE REVIEW

**Comment by niftylettuce** [comment]
Looking good, I'll cut a new release.

**Comment by niftylettuce** [comment]
Published as version `0.0.30` to NPM.

**Comment by niftylettuce** [comment]
Also, I'll be using this in <https://github.com/crocodilejs/crocodile-node-mvc-framework>, so thanks!

**Comment by livedo** [comment]
Thanks. Nice to hear it's going straight into use!

**Pull request merged**
