### PR TITLE
change United Kingdom to Olympic Great Britain

### PR DESCRIPTION
**Pull request by nitruxa**
change to Great Britain like http://www.olympic.org/great-britain

### CODE REVIEW

**Comment by nitruxa** [comment]
ping @evdb

**Comment by joeellis** [comment]
+1 to this, United Kingdom is showing up twice when it should be Great Britian.

**Comment by nitruxa** [comment]
@evdb pong!

**Comment by evdb** [comment]
Sorry for the delay, I've been travelling.

"Great Britain" and "United Kingdom" are two separate things. One is the physical island (and does not include Northern Ireland), the other is a country. See https://en.wikipedia.org/wiki/Great_Britain and https://en.wikipedia.org/wiki/United_Kingdom for details.

The olympic committee should really be called "United Kingdom", but I'm guessing their name is more historic than anything else (https://www.teamgb.com/about-boa). It was created in 1905, Northern Ireland was created in 1921. You should talk to them about changing their name :)

As to United Kingdom showing up twice that is most likely due to there being two entries - one for `gb` and one for `uk`. If you filter the countries by `assigned` you'll not see the `uk` entry which is just `reserved`. It might be worth creating a shortcut to do this so you could write `countries.assigned` instead of `countries.all`. Would that solve the duplicate problem?

**Comment by evdb** [comment]
As an aside, having lived in the UK, I would love (really LOVE), for the whole Great Britain vs United Kingdom thing to be finally sorted out. I seem to spend half my time scrolling around in enormous select lists looking for what the country is called this time. Is it Britain, England, Great Britain, UK, United Kingdom?

Just so you don't think that I feel your pain, I really do :)

**Comment by nitruxa** [comment]
@evdb can you provide a bit more info on what `reserved` and `assigned` stand for?

**Comment by evdb** [comment]
They are as described here: https://en.wikipedia.org/wiki/ISO_3166-1#Reserved_and_user-assigned_code_elements

`assigned` means that they are properly part of the standard, `reserved` means that they're not really part of the standard but are special in some way. So `uk` is reserved to prevent its use.

I've created issue #49 to deal with this when back at a desk (still on the road).

**Comment by nitruxa** [comment]
cool, thanks for info :)

**Pull request closed without merging**
