### PR TITLE
Use MIT license instead of AGPL

### PR DESCRIPTION
**Pull request by aduis**
Hey, 

it would be great if you could change to license to MIT instead of AGPL. Otherwise we have to use another packages :-/

Cheers, 
Andre

### CODE REVIEW

**Comment by evdb** [comment]
What part of AGPL prevents you from using the code? I'm curious.

**Comment by aduis** [comment]
According to my research I found out that we have to license our software under the same terms and we cannot do this. 

http://stackoverflow.com/questions/1960802/can-i-use-libraries-licensed-under-agpl-for-commercial-purposes

The GPL and AGPL require derived works to be released under the same terms, so if you use an AGPL library you will need to license your code under the AGPL or a compatible license.

If you use more than one library you should also take care that the license for each library is compatible with the license that you select for the derived work.

This link: http://www.fsf.org/licensing/licenses/gpl-faq.html and this link: http://www.fsf.org/licensing/licenses/index%5Fhtml#GPLCompatibleLicenses have a lot of useful information.

**Comment by evdb** [comment]
The first answer on that question is wrong. http://stackoverflow.com/a/11962162 is better.

The agpl places no licensing requirements on your code because it uses country-data. Installing the library is making an exact copy and then running it (http://www.gnu.org/licenses/gpl-faq.html#NoDistributionRequirements).

To make a comparison say you write a program which runs on Linux that renames a file. This program would be calling a gpl library (to do the file renaming) but it is obvious that this does not require the program to be gpl.

What the agpl does require is that if you modify the code in the country-data library then you need to share those modifications under the agpl. This is to encourage (enforce?) that improvements make it back to this GitHub repo for all to benefit from. 

I hope that clears it up that you can use the code with out license fears.

**Comment by evdb** [comment]
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0) sums it up rather nicely :)

**Comment by niftylettuce** [comment]
Just make it MIT!

**Comment by aduis** [comment]
Thanks for the big effort Edmund. That explains AGPL very good. Unfortunately the last link confirms our problem with AGPL. AGPL forces you to open source the project. 

Disclose Source 
You must disclose your source code when you distribute, publish or serve (i.e. through a web portal) modified software.
(https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0) )

It would be great if you can change you license but I can understand if you don't want to do this.

**Comment by evdb** [comment]
When I'm next at my desk I'll change the license to MIT and publish a new version to npm. Probably Monday, hopefully sooner. 

Regarding the open sourcing it only refers to modified code - that is to say code that came from a gpl code base that you the changed or incorporated into your project by copy and pasting. Just using it as a library does not make it modified as the code is unchanged. I'd hate for you not to use libraries that you may use, and I applaud your respect for the licenses on the code :)

**Comment by aduis** [comment]
Thanks that helps a lot. Ignoring licenses in packages that you use can cause a lot of trouble and I try to avoid it ;-)

**Comment by evdb** [comment]
v0.0.23 on npm now :)

**Pull request merged**
