### PR TITLE
data cleansed, tests added, continents added

### LINKED ISSUE #14: regions.js is missing North America
You've got many countries listed elsewhere, but no Canada or US. 
http://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_North_America

### PR DESCRIPTION
**Pull request by iancrowther**
resolves #14

### CODE REVIEW

**Comment by iancrowther** [comment]
@evdb pls review and merge if happy.  see previous PR re oceania..

**Comment by evdb** [comment]
Made a few little changes and have merged. Once tests have run on travis I'll bump the version and publish. Thanks for the contribution :)

**Comment by iancrowther** [comment]
welcome - I'm still working on it!!! so another minor PR is en route!

**Comment by iancrowther** [comment]
any news on the push to NPM?

**Comment by evdb** [comment]
v0.0.18 went out on npm a few minutes after the tests passed on travis :)

https://www.npmjs.com/package/country-data

**Comment by iancrowther** [comment]
ah great..

**Pull request merged**
